on:
  pull_request:
    types: [closed]

jobs:
  sample_action_job:
    runs-on: ubuntu-latest
    name: A job to save PR review comments
    steps:
    - name: Save PR comments in .storage
      id: sample
      uses: MichalBednarz/sample-action@master
      with:
        myToken: ${{ secrets.GITHUB_TOKEN }}
